### ISSUE TITLE
adding a Capability sub-TLV for a service 

### ISSUE THREAD

**Issue by muzixing** [ietf-wg-idr/draft-ietf-idr-5g-edge-service-metadata#17]
Currently in the draft, a site capability sub-TLV is defined. I think it is good.

However, I will suggest to add a service-oriented or per-service capability sub-TLV to distribute the capability that a service can use in a site. This is vital for an ingress router/controller to know how much resource can be accessed in a site for a service. I highly suggest to added one of it. For the details, we can discuss. 

Till now, I will recommend to introduce two ways of carrying capability data of a service in the sub-TLV. Firstly, we should allow the service to annouce the raw data, however, I do not suggest to do so, but let's allow this in this draft, and leave the details for future or other drafts. Secondly, we should support to distribute the unified format of the capability. It means in BGP, we only care about the value of the capability, we do not care what's the true meaning of the value means, it is defined by the service itself.

Thanks.

**Comment by lindadunbar** [comment]
We can add a Service-Oriented Capability Sub-TLV.
The service-oriented capability Sub-TLV is for distributing information regarding the capabilities of a specific service in a deployment environment. Depending on the deployment, a deployment environment can be an edge site or other types of environments. This information provides ingress routers or controllers with the available resources for the specific service in each deployment environment.
