### ISSUE TITLE
make the TLVs more flexible

### ISSUE THREAD

**Issue by muzixing** [ietf-wg-idr/draft-ietf-idr-5g-edge-service-metadata#18]
I see we defined several TLVs in the attribute. However, most of them do not have reserved bits. We may need to avoid this, because we cannot expect that we won't have any extension forever. Therefore, I highly suggest to reserve some bits in TLVs for future extension, like, making the length filed shorter？ or make it as a reserved filed if the length is a fixed value. Thanks.

**Comment by lindadunbar** [comment]
good suggestion. Changed the length to 8 bits and added reserved bits. 

            title="Preference Index Sub-TLV">
            <artwork><![CDATA[ 
   0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1
  +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
  |Site-Preference-Index Sub-Type | Length        | Reserved      |
  +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
  |                   Preference Index value                      |
  +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
