### ISSUE TITLE
New Route Target code point for constraining Metadata Path Attribute distribution

### ISSUE THREAD

**Issue by lindadunbar** [ietf-wg-idr/draft-ietf-idr-5g-edge-service-metadata#2]
From: Linda Dunbar 
Sent: Tuesday, November 21, 2023 12:52 PM
To: Jeffrey Haas <jhaas@pfrc.org>
Cc: Susan Hares <shares@ndzh.com>; idr@ietf.org
Subject: Question about your suggestion of getting a new Route Target code point for constraining Metadata Path Attribute distribution

Jeff, 

You have suggested to applying for a new Route Target code point for the purpose of constraining Metadata Path Attribute distribution. 

Do you mean applying for new SAFI? Currently the SAFI =132 is for Route Target Constrains. 
We assumed to use the same SAFI =132 for Ingress routers to send out the Route Target Membership NLRI Advertisements for the interested service IP prefix.  

Section 4 of the RFC4684 states that  “Route targets can then be expressed as prefixes”.

If it is not the new SAFI, what code point are you referring to?

Your advice is greatly appreciated. 

Linda

**Comment by suehares** [comment]
closed duplicate issue
