### ISSUE TITLE
Allowing to distribute raw delay info?

### ISSUE THREAD

**Issue by muzixing** [ietf-wg-idr/draft-ietf-idr-5g-edge-service-metadata#20]
I see we have defined a TLV to describe the delay prediction. How about let's allow the TLV or add a new TLV to carry the raw delay. Because it many cases, the ingress router/controller need the raw delay data to compute the E2E delay, so that they can choose the service instance/site with lowest delay.  I see  the F flag is added, is it for this purpose?

**Comment by lindadunbar** [comment]
when the Flag bit is set to 1:  Service Delay Predication is an integer in the range of 0-100, with 0 indicating that the service delay is negligible and 100 indicating that the site has the most significant delay compared to all other sites for the same service. 
Service Delay Predication Value (when the Flag bit is set to 0):the estimated delay time as defined in RFC5905.

**Comment by lindadunbar** [comment]
when the Flag bit is set to 0: the Service Delay Predication Value is the estimated delay time as defined in RFC5905.
I assume this is the "Raw Delay" you are asking for.
