### ISSUE TITLE
Remove A-flag in Service-Oriented Capacity Sub-TLV

### ISSUE THREAD

**Issue by muzixing** [ietf-wg-idr/draft-ietf-idr-5g-edge-service-metadata#23]
Hi authors,

When read the text in https://datatracker.ietf.org/doc/html/draft-ietf-idr-5g-edge-service-metadata-18#name-service-oriented-capability, I think it will be good to make abstract value as the default type of the capacity. If any other type of capacity unit will be defined in the future, it can be defined in other draft. Therefore, we should deleted the A-flag, making the “SO-CapValue field's value being the Service-Oriented Capability Abstract Value” as default. 

Also, we should make the SO-CapValue filed is a fixed field in this sub-TLV, it will be helpful when we add more fields into this sub-TLVs

**Comment by lindadunbar** [comment]
thank you very much for the suggestion. Having Abstract Value makes sense. Most likely the absolute value is difficult to collect and usually doesn't mean much for the ingress nodes. 

How about the the following?

     0  1   2  3  4  5 6  7  8  9  0  1  2   3  4 5 6  7  8  9   0  1  2  3  4  5 6  7  8  9  0  1
   +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
   | ServiceOriented Cap Sub-Type             |   Length                |   Reserved              |
   +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
   |                                         Resource Identifier                                                        |
   +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
   |    SO-CapValue      |                              Reserved                                                  |
   +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+ 

- Resource Identifier :  a logical term used to represent various
      types of resources, such as compute, network, power, or others,
      within the site reachable by the NLRI.  This identifier is
      consistent across all edge DCs and is determined by the specific
      deployment.  The purpose of the Resource Identifier is to indicate
      that the Service Oriented Capability Value pertains specifically
      to the resource identified by the Resource Identifier, which is
      carried in the ServiceOriented Cap Sub-TLV.

   - SO-CapValue:  Service-Oriented
      Capability Abstract Value is an integer in the range of 0-100,
      with 0 indicating that the site has the relatively lowest
      capability for the service and 100 indicating that the site has
      the highest capability for the service compared with all other
      sites that host the service.  When the value is outside the 0-100
      range, the value carried in this Sub-TLV is ignored.

**Comment by muzixing** [comment]
Regarding the format, you can see the issue 24. I pasted some suggested format in figure there.  
Regarding the text, 


Resource Identifier : a logical term used to represent the resource consumed by the service, which can be various
types of resources, such as compute, network, power, or others, within the site reachable by the NLRI. 

I do not think the ResourceID should remain consistent among edges. Normally it should only work within a site, in other words, it is a site-wide ID, which is used to identify a resource inside an edge site. But it might be used among multiple sites? to aggregate the resource among multiple sites? I would say this can be done. But the resource ID also complies to a site-wide ID?

Since this ID will appear in utilization sub-TLV, so it will be good to skip some capacity related text, and it is clear enough?

I am good to the text of service capacity, thank you so much!

**Comment by suehares** [comment]
The reason for no resource ID is included in this message.  
I'm adding this to the ](https://github.com/ietf-wg-idr/draft-ietf-idr-5g-edge-service-metadata-14/issues/24)
