### ISSUE TITLE
description of length 

### ISSUE THREAD

**Issue by muzixing** [ietf-wg-idr/draft-ietf-idr-5g-edge-service-metadata#25]
Please add description of length field of ALL sub-TLVs/TLVs in this document.

We do not how to process the length in the document. Like in section 4.2, what is the value? including the reserved field or not? should be clarified. I believe it should be 

"Length: Specifies the length of the value field (i.e., not including Type and Length fields) in terms of octets. "

same text is needed for section 4.3, section 4.5.1, section 4.5.3, section 4.6, 4.7

**Comment by lindadunbar** [comment]
Thanks for the suggestion. Yes, Length is the length of the Value field in octets.
