### ISSUE TITLE
Please list the field description in order in the TLV

### ISSUE THREAD

**Issue by muzixing** [ietf-wg-idr/draft-ietf-idr-5g-edge-service-metadata#26]
Please list the field description in order. Like section [Figure 3](https://datatracker.ietf.org/doc/html/draft-ietf-idr-5g-edge-service-metadata-18#figure-3): [Site Physical Availability Index Sub-TLV](https://datatracker.ietf.org/doc/html/draft-ietf-idr-5g-edge-service-metadata-18#name-site-physical-availability-i)

the order should be , PhyAvailIdx sub-Type, I flag, Reserved, Site-ID, Site Availability Percentage. 

Same for all sub-TLVs in the document,.

**Comment by lindadunbar** [comment]
Thanks for the suggestion. 
Changed per your suggestion.
