### ISSUE TITLE
Section 4.4.1 

### ISSUE THREAD

**Issue by suehares** [ietf-wg-idr/draft-ietf-idr-5g-edge-service-metadata#27]
Section 4.4.1 paragraph 2 - seems out of place with the current document. 

Text:/
   However, it is not necessary to include the Site Physical
   Availability Index Sub-TLV for every BGP Update message if there is
   no change to the Site Identifier or the Site Physical Availability
   value for the prefixes./

Discussion with Linda indicates that this sentence should be deleted.

**Comment by suehares** [comment]
Issue 16 - mentions this problem.  
https://github.com/ietf-wg-idr/draft-ietf-idr-5g-edge-service-metadata-14/issues/16

a) Routes = prefix + attributes.  
b) Section 6 addresses many issues, but this paragraph in section 4.4.1 denied item Routes = prefix + attributes

Issue 8 - also mentions the second paragraph in section 4.4.1
https://github.com/ietf-wg-idr/draft-ietf-idr-5g-edge-service-metadata-14/issues/8

**Comment by lindadunbar** [comment]
It is fixed in v22. will be uploaded as soon as IETF submission opens up.
