### ISSUE TITLE
TLV fields need to discuss lengths

### ISSUE THREAD

**Issue by jhaas-pfrc** [ietf-wg-idr/draft-ietf-idr-5g-edge-service-metadata#35]
The document now consistently uses TLV format throughout the whole document.  The length fields for a given TLV don't describe their expected lengths.  This is necessary for validation checks.

Most TLVs are fixed lengths.  For example, the Site-Prefere-Index TLV has 5 bytes of value.  This means that the length documentation should say "should be 5".

Update the length descriptions throughout the document.

**Comment by lindadunbar** [comment]
That is easy. Will add the following statement for all the Length field in the next Push: 

For the Site-Preference-Index (or X) Sub-Type, the length should be set to 5 (or Y)

**Comment by jhaas-pfrc** [comment]
This appears to be in the incoming commit.
