### ISSUE TITLE
Clarify Service Delay Prediction flags

### ISSUE THREAD

**Issue by jhaas-pfrc** [ietf-wg-idr/draft-ietf-idr-5g-edge-service-metadata#37]
Service delay prediction index has F and L flags.
The text describes what to do with L when F = 1.
The text needs to describe what to do with L when F=0.

My guess is "ignore it".  If so, update the text accordingly.

**Comment by lindadunbar** [comment]
Yes. The text is changed to the following: 

_"Flag (L) (1 bit):  Indicates the unit of  measurement for the Service Delay Prediction Value. When the F-flag is set to 0, L=0 specifies the 64-bit NTP Timestamp format, and L=1 indicates milliseconds. If the F-flag is set to 1, the L-flag value is ignored."_

**Comment by jhaas-pfrc** [comment]
This is addressed in the incoming commit.
