### ISSUE TITLE
raw measurements sub-tlv value?

### ISSUE THREAD

**Issue by jhaas-pfrc** [ietf-wg-idr/draft-ietf-idr-5g-edge-service-metadata#38]
The raw measurements sub-tlv (sub-tlv type 4) has a section for "raw packets or bytes measurement".  It's not clear if this is intended to be encapsulated in the value of this sub-tlv type 4 or not.

The raw bytes sub-tlv also uses a format that isn't consistent with the other TLVs in this draft.  It uses a one byte sub-type.

The fact that the raw value has a sub-type starting with 1, this appears to be a sub-sub-tlv.

**Comment by lindadunbar** [comment]
Yes, it is Sub-Sub-Type, intended to be encapsulated in the value field of Sub-Type 4. 

Do you think changing the description of the Value field to the following would be enough? 

 _"Value: The value filed can contain multiple types of raw measurements, each represented as a Sub-Sub-TLV."_
_"One example of a raw measurement metadata Sub-sub-TLV is defined below to
	convey the total number of packets or bytes transmitted over a
	specified period for a particular edge service address."_

**Comment by jhaas-pfrc** [comment]
The value description is fine.
What you also have is the same problem (unaddressed) as defining the general TLV formats.  In this sub-sub-tlv, you change format.  It means that you should say that the format has changed.

Better answer: make the tlv format the same as your existing TLVs.

The motivation for these things is you want to be able to write a consistent parser.  If you say all TLVs use a consistent format, even when the contents are not understood, you can at least do TLV syntax checks and validate the PDU is well formed.

**Comment by lindadunbar** [comment]
Okay, changed to 16 bits Sub-sub-Type (RawPacketsMeasure)

**Comment by jhaas-pfrc** [comment]
This appears to be addressed in the incoming commits.
