### ISSUE TITLE
Section 4.3.1 - Site Index Associated to Routes 

### ISSUE THREAD

**Issue by suehares** [ietf-wg-idr/draft-ietf-idr-5g-edge-service-metadata#8]
The Site index applies to a route from a site. 

The paragraph starting 
"However, it is unnecessary", does not follow general routing principles. 

Either remove or correct it.

**Comment by lindadunbar** [comment]
Is it better to change to "some BGP Update messages don't have the "Site Physical Availability Index sub-TLV attached"?

**Comment by suehares** [comment]
Alternate text: 

An egress router sets itself as next-hop for a BGP peer prior to sending an UPDATE prior with the Metadata Path Attribute with Site Physical Availability TLV.  As previously described, the Site Physical availability indicates the level of low latency services. 

[this replaces the first paragraph.]

**Comment by suehares** [comment]
adding changes to version 16.
