### ISSUE TITLE
Section 4.3.2 - Routing methodology here is problematic 

### ISSUE THREAD

**Issue by suehares** [ietf-wg-idr/draft-ietf-idr-5g-edge-service-metadata#9]
The methodology described works against the policy methodology. 

You are passing in the BGP Update: 
1) 1 or more routing prefixes (Anycast) with a specific Next Hop. 
2) Attribute with metrics of site index. 

BGP runs policy based on the information passed. 

The description indicates that you are referencing prefixes beyond the update you are passing. 

This is incorrect BGP procedure.  It must be fixed.

**Comment by lindadunbar** [comment]
The prefix is the loopback address for Router-X. The BGP UPDATE with a standalone Site Availability Index is NOT intended for resolving NextHop. 
The intent is for the new Site Physical Availability Index value to be applied to all the routes that have the following two constraints: a) have router-X as their next hop, and b) associated with site-ID.

**Comment by lindadunbar** [comment]
**How about the following writing for Section 4.3.2?** 

Upon receiving a BGP update message from Router-X, containing the loopback prefix of Router-X and the Metadata Path Attribute including the Site Physical Availability Index Sub-TLV, the ingress router applies the new Site Physical Availability Index value to all prefixes meeting two conditions: a) having Router-X as their next hop, and b) associated with the site-ID.
In the event of a site failure or degradation, the corresponding egress router can efficiently communicate the impact by issuing a single BGP UPDATE message containing the Site Physical Availability Index with the egress router's loopback address. This method eliminates the need for multiple route withdrawal messages for all affected prefixes, streamlining the network's response to the failure.

**Comment by suehares** [comment]
Upon receiving a BGP update message from Router-X, containing the Update with the Metadata Path Attribute with the Site Physical Availability Index Sub-TLV,  the next-hop should be the loopback of Router-X. 

The local BGP peer uses local policy to evaluate the route (prefix and path attributes).  When the local policy processes the Metadata Attribute with the Site Physical availability, it will use the site availability index to efficiently reduce or increase the preference for all BGP routes with the Router-X next-hop (loopback).

**Comment by suehares** [comment]
closed with additions to -16.

**Comment by suehares** [comment]
adding to -16.
